### PR TITLE
add prefix for views cid when property __name__ provided

### PR DESCRIPTION
**Pull request by jripault**
Add the possibility to prefix the cid of view to facilitate debugging. Pass the property **name** in the constructor's options.

### CODE REVIEW

**Comment by loicfrering** [comment]
I'm asking myself if this behavior should be optional or not, what do you think?

**Comment by jripault** [comment]
I think it should be mandatory if we could prefix models and collections too because it would allow to clearly debug everything. But I didn't find a good way to do it as Resthub doesn't propose Model and Collection abstraction.
So I'd stick to 'optional' for now

**Comment by sdeleuze** [comment]
I am ok with mandatory. Can't we do some monkey patching to get this behaviour in Model and Collection too ?

**Comment by loicfrering** [comment]
Thanks!

**Pull request merged**
