### PR TITLE
Manage pubsub handlers

### PR DESCRIPTION
**Pull request by bmeurant**
This PR is related to #10.

Some important points have to be discussed related to this PR and issue #10.
1. **syntax and object keys problem**

Initially we wanted to **mimic Backbone events hash** in order to registrer automatically pubsub handers.

i.e., as Backbone do with events ... 

```
Backbone.View.extend ({       
    events: {
       "focusin ul.thumbnails li.thumbnail a":"elemFocused",
       "focusout ul.thumbnails li.thumbnail a":"elemFocused",
       "click li.thumbnail":"hideTooltips"
    }
});
```

... implement pubsub handlers management:

```
Backbone.View.extend ({       
    handles: {
       "type1":"callback1",
       "type2":"callback2",
       "type3":"callback3"
    }
});
```

This particular sample is OK but it seems to me an important feature **to be able to define globally (in view or even in app) some shared events, defined once and reused everywhere**. Something like : 

```
App.Events.TYPE3 = "type3";

Backbone.View.extend({       
    handles: {
       "type1":"callback1",
       "type2":"callback2",
       // this is not valid !
       TYPE3:"callback3"
    }
});
```

But this is not possible in javascript (it is surely obvious to javascript experts but I did not realize that in a first approach) as well explained here : http://mathiasbynens.be/notes/javascript-properties.

So I had to find another syntax based on nested arrays : 

```
Backbone.View.extend({
    handles:[
        ["type1", "callback1"],
        ["type2", "callback2"],
        [TYPE3, "callback3"],
        ["type4", function () {this.counts[5] += 1;}]
    ]
});
```

I preferred this first syntax but this one works ! @loicfrering: Is there another solution ?
1. **Inheritance strategy**

I implemented this Backbone.View extension by **extending directly `Backbone.View`** (as commonly done in Backbone extensions) and not defining our own `Backbone.View` extension (e.g. `Backbone.Resthub.View`).

Doing this:
- our extension is completely transparent in a user point of view : he only have to extend `Backbone.View` as he always done before.
- compatibility with others `Backbone.View` extension could be easier because they already extend `Backbone.View` and obviously not `Backbone.Resthub.View`. But I'm not fully convinced of that because all extensions I saw before were inline `View` extensions (simply adding `_.extend(Backbone.View.prototype, {`) that will be compatible anyway ...

But it necessitates some boilerplate to call handles parsing on View constructor while keeping `View` behaviour safe: 

```
// Backbone.View extension
// -----------------------

var originalPrototype = Backbone.View.prototype;
var originalConstructor = Backbone.View;
var originalExtend = Backbone.View.extend;

Backbone.View = function () {
    originalConstructor.apply(this, arguments);
    this.subscribeHandles();
};

// Restore original prototype
Backbone.View.prototype = originalPrototype;
Backbone.View.extend = originalExtend;
```

Is this solution a good one ? Do we have other options (at least one : make a `Resthub.View`) ? Is this the goal we want to achieve (in architectural terms) ?

@sdeleuze, @loicfrering : I am not sure of what solution I prefer and I'd like to discuss this point together.

### CODE REVIEW

**Comment by bmeurant** [comment]
test are fines here ...

**Comment by loicfrering** [comment]
FYI tests are failing for me too with phantomjs but not in my browser. I'll have a closer look to this PR tonight or tomorrow :)

**Comment by loicfrering** [comment]
:rainbow:

**Comment by bmeurant** [comment]
I got it !!

Due to some f@#!_?|% `this binding` problem !  ... @loicfrering : you will have to explain me :-) (and say me if there is better solution)

**Comment by bmeurant** [comment]
After our discussion :
- pubsub library disapeared for a simple `Backbone.Events` extension : this define a global pubsub channel for native `Backbone.Events` management (but with any custom user-defined event)
- new pubsub events declaration in Views are merged with `Backbone.View` DOM events

e.g: 

```
events:{
     "click #btn1":"buttonClicked",
     "click #btn2":"buttonClicked",
     "!global":"globalFired",
     "!global1":"globalFired",
     "!globalParams":"globalFiredParams"
},
```

To differienciate global events from Backbone DOM event declarations (managed differently by Backbone as usual), all global events must start with `!`.

Registering of all global events on a view is, as DOM events, executed on constructor in `delegateEvents()` method that parse the `events` hash or take a custom hash in parameter to register dynamically after constructor : 

```
testView3.delegateEvents({"!global":"globalFired"});
```

Unregistering of global events is done as Backbone DOM events once and for all with `undelegateEvents()` method (called by `dispose()` method).

These two methods are uses internally but should not be exposed to developpers (in fact, they are public but should not be emphasized in doc)

To manage global events, we should promote direct usage of `Backbone.Events` API : 

```
// subscibe to one event (do not forget this)
Pubsub.on("test-event", function () { ... }, this);

// subscribe to multiple events
Pubsub.on("test-event test-event2", function () { ... }, this);

// trigger one event
Pubsub.trigger("test-event");

// trigger multiple events
Pubsub.trigger("test-event test-event2");

// unsubscribe from one event
Pubsub.off("test-event");

// unsubscribe from multiple events
Pubsub.off("test-event test-event2");

// unsubscribe from all
Pubsub.off();
```

Management of DOM events in view is not modified and is explained in Backbone documentation.

**Pull request merged**
